version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase-if-necessary
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: daily
    groups:
      compose-images:
        patterns:
          - "*"
